// Simple test file to verify compilation
#include "../include/VulkanRenderer.h"
#include "../include/WindowManager.h"
#include "../include/GameEntity.h"
#include "../include/InputManager.h"
#include "../include/Camera.h"
#include "../include/Mesh.h"
#include "../include/MeshRenderer.h"
#include "../include/AssetManager.h"
#include "../include/Component.h"
#include "../include/GameObject.h"
#include "../include/RenderComponent.h"
#include "../include/PhysicsComponent.h"
#include "../include/CollisionSystem.h"
#include "../include/Timer.h"
#include "../include/Logger.h"
#include "../include/FileUtils.h"
#include "../include/Config.h"
#include "../include/ResourceManager.h"
#include "../include/EventSystem.h"
#include "../include/StateMachine.h"
#include "../include/ExampleState.h"
#include "../include/Profiler.h"
#include "../include/ShaderCompiler.h"
#include "../include/PhysicsWorld.h"
#include "../include/AudioEngine.h"
#include "../include/Material.h"
#include "../include/ShaderProgram.h"
#include "../include/Light.h"
#include "../include/DirectionalLight.h"
#include "../include/PointLight.h"
#include "../include/SpotLight.h"
#include "../include/LightManager.h"
#include "../include/GUIElement.h"
#include "../include/Button.h"
#include "../include/GUIManager.h"
#include "../include/CharacterController.h"
#include "../include/Inventory.h"
#include "../include/Quest.h"
#include "../include/QuestManager.h"
#include "../include/ParticleSystem.h"
#include "../include/Animation.h"
#include "../include/AnimationController.h"
#include "../include/ScriptComponent.h"
#include "../include/BehaviorTree.h"
#include "../include/BehaviorTreeExample.h"

int main() {
    // This is just a compilation test - we won't actually run this
    return 0;
}